Chunk
java-park-mail-ru/Chunk-09-2017 pull request #1
Opened 2017-09-20 22:53 UTC by TrubnikovDmitriy

2017-09-21 09:59 UTC, KSolovyev commented
Сегодня уже не успею посмотреть

2017-09-21 12:38 UTC, KSolovyev requested changes

2017-09-21 12:38 UTC, KSolovyev commented on src/main/java/application/views/Response.java
> +public class Response {
зачем нужно этот базовый класс? Зачем здесь наследование? Уберите его

2017-09-21 12:38 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +    // Getters & setters
и так понятно, что геттеры и сеттеры, давайте уберем

2017-09-21 12:38 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +    public static User findUser(
это в UserService должно быть

2017-09-21 12:38 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +@SuppressWarnings("unused")
а какие методы у вас тут неиспользуемые?

2017-09-21 12:38 UTC, KSolovyev commented on src/main/java/application/models/UpdateUser.java
> +@SuppressWarnings("unused")
здесь не должно быть неиспользуемых методов

2017-09-21 12:38 UTC, KSolovyev commented on src/main/java/application/controllers/Controllers.java
> +        // Валидация
валидацию надо убрать, либо в сервис UserService, либо в отдельный класс. В контроллере ее быть не должно

2017-09-21 12:38 UTC, KSolovyev commented on src/main/java/application/controllers/Controllers.java
> +                    HttpStatus.GONE
403 должно быть. Ну или что-то такое

2017-09-21 12:59 UTC, TrubnikovDmitriy commented on src/main/java/application/models/User.java
> +@SuppressWarnings("unused")
setUsername, setPassword, setEmail

2017-09-26 11:03 UTC, KSolovyev requested changes

2017-09-26 11:03 UTC, KSolovyev commented on pom.xml
> +            <groupId>org.apache.tomcat.embed</groupId>
Вот это лишнее, скорее всего

2017-09-26 11:03 UTC, KSolovyev commented on src/main/java/application/controllers/Controllers.java
> +        this.responseHeader.set("Access-Control-Allow-Credentials", "true");
у народа работает с аннотацией `@CrossOrigin`. Только нужно указать ваш точный origin:
https://www.%s.heroku.com

2017-09-26 11:03 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +    public String getPassword() {
пароль надо пометить как `@JsonIgnore`

2017-09-27 21:55 UTC, KSolovyev approved these changes

2017-09-27 21:55 UTC, merged

2017-09-27 21:56 UTC, KSolovyev commented
надо либо поребейзить девелоп на мастер, либо мастер вмержить в девелоп