РК №2
java-park-mail-ru/Chunk-09-2017 pull request #2
Opened 2017-10-18 19:34 UTC by TrubnikovDmitriy

2017-10-19 10:11 UTC, Badya requested changes
Рекомендую пересмотреть иерархию классов - абстракции делают слишком много - реализации же не делают ничего что позволило бы их называть "реализацией" - возможно лучше вообще определить интерфейс в случае с сервисом

2017-10-19 10:11 UTC, Badya commented on src/main/resources/db/migration/V1__init.sql
> +GRANT ALL ON SCHEMA public TO PUBLIC;
Очень стремное решение, конечно в нашем случае не столь критичное - но все таки так делать не стоит)

2017-10-19 10:11 UTC, Badya commented on src/test/java/application/unit/UserDaoJpaTest.java
> +public class UserDaoJpaTest extends UserDaoAbstractTest {
Вообще не самая лучшая схема хранить тесты в абстрактном классе и делать такое наследование

2017-10-19 10:11 UTC, Badya commented on src/main/java/application/services/UserServiceAbstract.java
> +public abstract class UserServiceAbstract {
Странное использование абстракции впринципе - по сути этот абстрактный класс реализует все.

2017-10-19 10:11 UTC, Badya commented on src/main/java/application/controllers/UserController.java
> +    private final UserServiceAbstract service;
Ваш сервис теперь выбрасывает кучу исключений которые по хорошему надо обработать

2017-10-19 10:11 UTC, Badya commented on src/main/java/application/services/UserServiceAbstract.java
> +    public abstract static class UserServiceException extends RuntimeException {
Исключения это не плохо - но заполнять ими один файл вместе с сервисом при таком их количестве и должной иерархии не стоит - можно вынести в отдельный пакет даже и собрать там пачку файлов с этими исключениями

2017-10-19 11:14 UTC, TrubnikovDmitriy commented on src/main/java/application/controllers/UserController.java
> +    private final UserServiceAbstract service;
Я думал, что @ExceptionHandler(UserServiceException.class) этим занимается?

2017-10-27 10:01 UTC, Badya requested changes

2017-10-27 10:01 UTC, Badya commented on src/main/java/application/services/user/UserServiceJpa.java
> +        } catch (EmptyResultDataAccessException e1) {
Это очень странное решение - нужно придумать как обойти вложенность

2017-10-27 10:01 UTC, Badya commented on src/main/java/application/services/user/UserServiceTools.java
> +        if (user.getPassword() != null) {
В Java все что под if работает по принципу Short-circuit evaluation

то есть вместо 2х if можно написать `if (a != null && a.getSome() > VALUE)` и мы не когда не получим NPE

2017-10-27 10:01 UTC, Badya commented on src/main/java/application/services/user/UserServiceExceptions.java
> +public class UserServiceExceptions {
Все это можно вообще в отдельную пакадж вынести и не пихать в один класс

2017-10-27 10:01 UTC, Badya commented on src/main/java/application/models/UserModel.java
> +public class UserModel {
Что бы не запутаться лучше чтобы это было абстракт, еще лучше заменить наследование на композицию

2017-10-30 11:41 UTC, Badya approved these changes

2017-10-30 11:41 UTC, merged