РК №3
java-park-mail-ru/Chunk-09-2017 pull request #3
Opened 2017-11-15 11:04 UTC by TrubnikovDmitriy

2017-11-15 12:41 UTC, KSolovyev commented
checker упал

2017-11-15 13:19 UTC, isopov commented
1. `<version>2.0.0.M4</version>` - давайте, может, обновимся? уже 2.0.0.M6 вышла
2. `<version>${h2.version}</version>` - непонятно, зачем нужно
3. Выглядит очень-очень странно - это один из модулей самого спринга, и никто не гарантирует, что старая версия модуля будет работать с новым ядром. Даже если это так и для чего-то надо - тут нужен комментарий зачем и какие проблемы этим мы обходим.
```
<artifactId>spring-websocket</artifactId>
<version>4.2.4.RELEASE</version>
```
4. flyway-maven-plugin - а это зачем?
5. spring-boot-starter-test не в тестовом scope
6. hibernate-entitymanager - зачем эта зависимость? У неё в названии написано "(deprecated - use hibernate-core instead) Hibernate JPA Support" (а hibernate-core тянется через spring-boot-starter-data-jpa)
7. spring-boot-starter-jdbc - эта зависимость тоже тянется из spring-boot-starter-data-jpa
8. TestUtils - очень странный класс, помечен `@Component` но нигде берется из контекста.
9. `public static final Random RANDOM = new Random(new Date().getTime());` - а вы не хотите сделать тесты более предсказуемыми и одинаковыми?
10. TestUtils.MAPPER - лучше использовать в тестах ObjectMapper, взятый из контекста - к нему уже будут применены нестандартные конфиги, такие же, как и в боевом коде.
11. GameAbstract.mapper - к боевому коду это тоже относится
12. Расскажите, что такое GameSocketController1xx и GameSocketController2xx
13. `new Thread(() -> chooseAction(code, jsonNode, session)).run();` - а это что такое?
14.  `System.err.println` - логирование!

2017-11-15 13:19 UTC, isopov requested changes
Ревью в комментариях будет проходить

2017-11-15 13:54 UTC, TrubnikovDmitriy commented
12 и 13 пункты

2017-11-15 13:59 UTC, TrubnikovDmitriy commented
12 и 13 пункты
Мы решили заморочиться и дать возможность игроку выбирать к какой игре он хочет подключиться (фактически лобби для игр создать). Выглядеть это будет примерно так:

2017-11-15 14:13 UTC, TrubnikovDmitriy commented
12 и 13 пункты
Мы решили заморочиться и дать возможность игроку выбирать к какой игре он хочет подключиться (фактически лобби для игр создать). Выглядеть это будет примерно так:
![image](https://user-images.githubusercontent.com/22626369/32839963-3fd92a28-ca27-11e7-9d94-3e4c06240790.png)

На фронтенде, нам советовали создать свой "надпротокол" над вебсокетами. То есть заключить некий контракт между клиентом и сервером. Коды статусов этого контракты описаны вот здесь: https://github.com/java-park-mail-ru/Chunk-09-2017/blob/16f3491a86332e3e5af655de8a3500aa583fe6a5/src/main/java/application/services/game/GameSocketStatusCode.java#L5

Из-за этого все несколько усложнилось и логику решено было разделить на 2 части:
1) Controller1xx. Подготовка к игре (формирования поля, добавление/удаление игроков/ботов). Причем все изменения должны отображаться у остальных игроков. Например - игрок зашел в готовящуюся игру - все кому это интересно, должны быть об этом уведомлены, соответственно тут тоже были нужны сокеты.
2) Controller2xx. Сама игра - ходы игроков, ходы ботов, проверка на валидность, конец игры, оповещение игроков и так далее.

Так как игра пошаговая и игроки объединены по своим локальным "группкам" было решено, что можно попробовать заюзать многопоточность. На запрос пользователя создается отдельный поток, который далее работает в своей игре. Это было сделано из тех соображений, чтобы 2 разные, не связанные друг с другом игры, не выполнялись в одном потоке, а соответственно и не ждали друг друга.

2017-11-15 16:58 UTC, isopov commented
>Так как игра пошаговая и игроки объединены по своим локальным "группкам" было решено, что можно попробовать заюзать многопоточность.

Логики не вижу. "Так как игра пошаговая... многопоточность". Я бы делал наоборот - так как игра пошаговая - не использовать вообще многопоточность (только для таймаутов на действия пользователей, но без этого в minimal viable product можно и обойтись).

2017-11-16 04:42 UTC, TrubnikovDmitriy commented
Создание новых потоков убрал.
Все пункты, за исключением 9го, поправил

2017-11-29 14:24 UTC, isopov commented
1. Я сильно удивлён, что такая комбинация работает:
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc(print = MockMvcPrint.NONE)
```
Впрочем, у вас там никаких завивимостей на настоящий сервер нет, и нормальная комбинация работает тоже
```
@SpringBootTest
@AutoConfigureMockMvc(print = MockMvcPrint.NONE)
```
2. В том же тесте неиспользуемое (внезапно IDE не всё может отловить, да?):
```
   @Rule
    public ExpectedException expected = ExpectedException.none();
```
А также непонятно зачем нужные комментарии, импорты...
3. `.andDo(print())` в тестах (тем более по два в одном) - это по сути System.out.println - я то лично вообще не понимаю зачем в тестах логирование нужно, а уж такое только для дебажных целей, чтобы это не комитить.
4. TestUtils.TestPlayer & TestUtils.TestPlaystep где-то используются?
5. GameBusinessLogicTest - этому тесту вообще не нужен Spring (и sysout-ы из него уберите)
6. `interface UserDaoTest` - WAT? зачем это нужно?
7. `UserDaoJpaTest` вполне может быть `@SpringBootTest(webEnvironment = WebEnvironment.NONE)` - без всякого веб-слоя.
8. В src/test/resources/application.properties строки
```
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:backend;DB_CLOSE_DELAY=-1
```
лишние - тесты замечатеьно работают и без них (автоконфигурация spring-boot тестов подхватывает H2 из classpath)
А в целом - хорошие тесты, надеюсь вы ими прониклись, а не прокляли меня, пока их писали ;-)
9. Почему зависимость на spring-websocket, а не на spring-boot-starter-websocket ?
10. Зависимость на spring-boot-starter-jdbc можно удалить - она тянется через spring-boot-starter-jdbc
11. `GameException.session` - это очень нестандартное и неожиданное содержимое исключения. Давайте попробуем, всё-таки порефакторить, и вынуть вебсокетную сессию оттуда...

2017-12-10 12:26 UTC, merged